# Generated by Django 6.0.4 on 2026-04-14 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('security', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accessusers',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='databasebackups',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='groupmodule',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='module',
            name='permits',
            field=models.ManyToManyField(blank=True, to='auth.permission', verbose_name='Permisos'),
        ),
        migrations.AddField(
            model_name='grouppermission',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.module'),
        ),
        migrations.AddField(
            model_name='groupmodule',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='security.module'),
        ),
        migrations.AddField(
            model_name='module',
            name='module_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='security.moduletype', verbose_name='Tipo de Módulo'),
        ),
    ]
